// client/projects/shared/blocks/blocks/text/text.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {Block} from '@jaspero/fb-page-builder';
import {COMMON_OPTIONS} from '../common-options.const';
import {CommonBlockComponent, CommonOptions} from '../common.block';

interface Options extends CommonOptions {
  title?: string;
  titleWidth?: string;
  subtitle?: string;
  subtitleWidth?: string;
  theme?: string;
}

@Block({
  label: 'Text',
  icon: 'text_fields',
  previewValue: {
    title: 'SECURITY SYSTEM UNIFICATION',
    titleWidth: 'auto',
    subtitle: 'An expert team of system engineers and programming prowess',
    subtitleWidth: 'auto',
    theme: 'theme-accent',
    ...COMMON_OPTIONS.default
  },
  form: {
    segments: [
      {
        title: 'Content',
        icon: 'article',
        fields: [
          '/title',
          '/titleWidth',
          '/subtitle',
          '/subtitleWidth',
          '/theme'
        ]
      },
      ...COMMON_OPTIONS.segment
    ],
    schema: {
      properties: {
        title: {type: 'string'},
        titleWidth: {type: 'string'},
        subtitle: {type: 'string'},
        subtitleWidth: {type: 'string'},
        theme: {type: 'string'},
        ...COMMON_OPTIONS.properties
      }
    },
    definitions: {
      title: {label: 'Title'},
      titleWidth: {label: 'Title Width'},
      subtitle: {label: 'Subtitle'},
      subtitleWidth: {label: 'Subtitle Width'},
      theme: {
        label: 'Theme',
        component: {
          type: 'select',
          configuration: {
            dataSet: [
              {name: 'Light', value: 'theme-light'},
              {name: 'Dark', value: 'theme-dark'},
              {name: 'Accent', value: 'theme-accent'},
            ]
          }
        }
      },
      ...COMMON_OPTIONS.definitions
    }
  }
})
@Component({
  selector: 'jms-text',
  templateUrl: './text.component.html',
  styleUrls: ['./text.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TextComponent extends CommonBlockComponent<Options> {}
<section class="t" [ngClass]="data.theme">
	<h1 *ngIf="data.title" class="t-title" [style.max-width]="data.titleWidth">{{data.title}}</h1>
	<p *ngIf="data.subtitle" class="t-subtitle" [style.max-width]="data.subtitleWidth">{{data.subtitle}}</p>
</section>

// web-wip/src/lib/Text.svelte
<script>
	export let data = {
		theme: 'accent', // {'dark' || 'light' || 'accent'}
		title: 'SECURITY SYSTEM UNIFICATION',
		titleWidth: 'auto',
    subtitle: 'An expert team of system engineers and programming prowess',
    subtitleWidth: 'auto',
	}
</script>

<section class="t theme-{data.theme}">
	{#if data.title}<h1 class="t-title" style="max-width: {data.titleWidth};">{data.title}</h1>{/if}
	{#if data.subtitle}<p class="t-subtitle" style="max-width: {data.subtitleWidth};">{data.subtitle}</p>{/if}
</section>

<style>
	.theme-dark {
		--bg: var(--c-darker);
		--fg: var(--c-lighter);
	}
	.theme-light {
		--bg: var(--c-light);
		--fg: var(--c-darker);
	}
	.theme-accent {
		--bg: var(--c-blue);
		--fg: var(--c-lighter);
	}
	.t {
		background: var(--bg);
		color: var(--fg);
		text-align: center;
		padding: 4.5rem 0;
	}
	.t-title {
		padding: 0 1rem;
		font-size: var(--s-xl);
		font-family: var(--f-title);
		font-weight: normal;
		max-width: 70rem;
		margin: 0 auto;
	}
	.t-subtitle {
		padding: 0 1rem;
		font-size: var(--s-m);
		margin: 0 auto;
	}
</style>
